begin;
   savepoint create_tb_disciplinas;
   CREATE TABLE IF NOT EXISTS disciplinas (
      id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      codigo                VARCHAR(100),
      nome                  VARCHAR(100),
      turmas                INT,
      discentes             INT,
      cancelamentos         INT,
      reprovacoesMedia      INT,
      reprovacoesNota       INT,
      reprovacoesFalta      INT,
      reprovacoesMediaFalta INT,
      reprovacoesNotaFalta  INT,
      trancamentos          INT,
      insucessos            INT,
      semestre              VARCHAR(100),
      departamento          VARCHAR(100),
      curso                 VARCHAR(100)
   );
commit;