BEGIN;

-- TABELA ORIGINAL

SAVEPOINT create_tb_disciplinas;

CREATE TABLE IF NOT EXISTS public.disciplinas (
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                VARCHAR(100),
    nome                  VARCHAR(100),
    turmas                INT,
    discentes             INT,
    cancelamentos         INT,
    reprovacoesMedia      INT,
    reprovacoesNota       INT,
    reprovacoesFalta      INT,
    reprovacoesMediaFalta INT,
    reprovacoesNotaFalta  INT,
    trancamentos          INT,
    insucessos            INT,
    semestre              VARCHAR(100),
    departamento          VARCHAR(100),
    curso                 VARCHAR(100)
);

-- SCHEMA DO DATA WAREHOUSE 

CREATE SCHEMA IF NOT EXISTS dw AUTHORIZATION postgres;
SET search_path TO dw;

-- DIMENSÃO

CREATE TABLE IF NOT EXISTS dw.dim_disc (
    srk_disc INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    cod_disc VARCHAR(100) NOT NULL,
    nm_disc VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_tmp (
    srk_tmp INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ano INT NOT NULL,
    sem_ano VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_dpt (
    srk_dpt INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nm_dpt VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_cur (
    srk_cur INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome_cur VARCHAR(100) NOT NULL
);

-- FATO

CREATE TABLE IF NOT EXISTS dw.fato_insuc (
    srk INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    srk_disc INT NOT NULL REFERENCES dw.dim_disc(srk_disc) ON DELETE CASCADE,
    srk_tmp INT NOT NULL REFERENCES dw.dim_tmp(srk_tmp) ON DELETE CASCADE,
    srk_dpt INT NOT NULL REFERENCES dw.dim_dpt(srk_dpt) ON DELETE CASCADE,
    srk_cur INT NOT NULL REFERENCES dw.dim_cur(srk_cur) ON DELETE CASCADE,
    turm INT DEFAULT 0,
    discen INT DEFAULT 0,
    canc INT DEFAULT 0,
    rpv_med INT DEFAULT 0,
    rpv_not INT DEFAULT 0,
    rpv_fal INT DEFAULT 0,
    rpv_med_fal INT DEFAULT 0,
    rpv_not_fal INT DEFAULT 0,
    tranc INT DEFAULT 0,
    insuc INT DEFAULT 0
);


COMMIT;