BEGIN;

-- TABELA ORIGINAL

SAVEPOINT create_tb_disciplinas;

CREATE TABLE IF NOT EXISTS public.disciplinas (
    id                    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                VARCHAR(100),
    nome                  VARCHAR(100),
    turmas                INT,
    discentes             INT,
    cancelamentos         INT,
    reprovacoesMedia      INT,
    reprovacoesNota       INT,
    reprovacoesFalta      INT,
    reprovacoesMediaFalta INT,
    reprovacoesNotaFalta  INT,
    trancamentos          INT,
    insucessos            INT,
    semestre              VARCHAR(100),
    departamento          VARCHAR(100),
    curso                 VARCHAR(100)
);

-- SCHEMA DO DATA WAREHOUSE 

CREATE SCHEMA IF NOT EXISTS dw AUTHORIZATION postgres;
SET search_path TO dw;

-- DIMENSÃO

CREATE TABLE IF NOT EXISTS dw.dim_disciplinas (
    id_disciplina INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(100) NOT NULL,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_tempo (
    id_tempo INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ano INT NOT NULL,
    semestre VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_departamento (
    id_departamento INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome_departamento VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS dw.dim_curso (
    id_curso INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome_curso VARCHAR(100) NOT NULL
);

-- FATO

CREATE TABLE IF NOT EXISTS dw.fato_disciplinas (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    id_disciplina INT NOT NULL REFERENCES dw.dim_disciplinas(id_disciplina) ON DELETE CASCADE,
    id_tempo INT NOT NULL REFERENCES dw.dim_tempo(id_tempo) ON DELETE CASCADE,
    id_departamento INT NOT NULL REFERENCES dw.dim_departamento(id_departamento) ON DELETE CASCADE,
    id_curso INT NOT NULL REFERENCES dw.dim_curso(id_curso) ON DELETE CASCADE,
    turmas INT DEFAULT 0,
    discentes INT DEFAULT 0,
    cancelamentos INT DEFAULT 0,
    reprovacoesmedia INT DEFAULT 0,
    reprovacoesnota INT DEFAULT 0,
    reprovacoesfalta INT DEFAULT 0,
    reprovacoesmediafalta INT DEFAULT 0,
    reprovacoesnotafalta INT DEFAULT 0,
    trancamentos INT DEFAULT 0,
    insucessos INT DEFAULT 0
);


COMMIT;